---
title: "Projeto"
author: "Jessica Sena (mais ou menos, quase nada...)"
date: "`r Sys.Date()`"
output_dir: "."
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

## Relatório

> Projeto de conclusão


**Negrito**  *itálico* `html`

```{r dados}
library(tidyverse)
## Leitura dos dados
survey <- read_csv("Base/br-capes-colsucup-prog-2019-2020-11-30.csv",  
                   locale = locale())

## Separação da primeira linha com a descr. da variável
#descricao_survey <- survey %>% 
#  slice(n = 1)
#print (descricao_survey)

# Observações da base
survey_limpo <- survey %>% 
  slice(n = 1:n()) # n() total de linhas na base
```


## Descrição da variável: Área de atuação

### Tabela

```{r, echo=TRUE}
tabela_area <- arrange(count(survey_limpo, NM_GRANDE_AREA_CONHECIMENTO), -n)
#survey_limpo %>% count(NM_GRANDE_AREA_CONHECIMENTO) %>% arrange(-n) %>% kable()

knitr::kable(tabela_area)
```

### Gráfico de Barras

Meu lindo gráfico de barras a seguir
```{r, echo=TRUE, eval=TRUE}
survey_limpo %>% 
  count(NM_GRANDE_AREA_CONHECIMENTO) %>% 
  ggplot() +
    geom_bar(aes(x = reorder(NM_GRANDE_AREA_CONHECIMENTO, n), 
                 y = n, fill = NM_GRANDE_AREA_CONHECIMENTO) , 
             stat = "identity", show.legend = FALSE
             ) +
  coord_flip() + ylab("Quantidade de faculdades") + xlab("STATUS JURIDICO") +
  labs(fill = "Status Jurídico")
```





